"""End-to-end tests for src.io.ili_reader against real vendor example files.

EXPECTED has two count baselines per file:

  * features_total           — raw rows kept (matches the vendor's "Total
                               rows on Defects sheet" figure when known).
  * features_for_assessment  — what ILIRun.features_for_assessment() returns;
                               cluster children excluded. Matches the
                               vendor's executive-summary "total metal-loss
                               features assessed" figure where confirmed.

Values are PDF-validated where annotated; otherwise pinned to the parser's
first green pass against the file and flagged "baseline only" in a comment.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from src.io.ili_reader import ILIReader, _norm
from src.models import FeatureIdentification, Surface
from src.validation import QAFlagCode

EXAMPLES = Path(__file__).resolve().parents[1] / "examples"

# Required canonical fields the reader contract guarantees on output Features
# (every feature must have these — depth/wt/length/width/abs_distance/surface).
_REQUIRED_FIELDS_ON_FEATURE = (
    "abs_distance_m",
    "joint_number",
    "depth_pct_wt",
    "wt_mm",
    "length_mm",
    "width_mm",
)

# Per-file expectations. Tolerance: ±2 % per the spec.
EXPECTED = {
    "8-9100-13964_28IP1IP2_Pipe_Tally_run1_.xlsx": {
        "sheet": None,  # single-sheet; the sheet name is autogenerated junk
        "header_idx": 0,
        "features_total": 16057,                # baseline only
        "features_for_assessment": 16057,       # no Description col → no children tagged
        "min_joints": 2000,
        "expected_qa_codes": [],
        "tag": "NGP 2019 single-sheet",
    },
    "1YCF_Pipeline_Listing__run2_.xlsx": {
        "sheet": "Defects",
        "header_idx": 1,
        # HMEL PDF executive summary: 106,969 metal-loss features assessed;
        # 29,479 features formed 11,768 clusters. Reader now sits at
        # 106,969 (exact). The +5 in features_total vs the prior baseline
        # (136,449 → 136,454) is the non-metal-loss rows (5 of them)
        # that the API change keeps in `run.features` and filters out
        # at `features_for_assessment()` time.
        "features_total": 136454,
        "features_for_assessment": 106969,
        "min_joints": 6000,
        "expected_qa_codes": [],
        "tag": "NGP 2025 multi-sheet (HMEL IPS1-IPS2)",
    },
    "1ZSV_Pipeline_Listing.xlsx": {
        "sheet": "Defects",
        "header_idx": 1,
        # GAIL Kandla-Samakhiali PDF: 333 metal-loss features.
        # The reader now keeps 38 non-metal-loss rows (37 dents + 1
        # crack) in `run.features` so the raw total is 371 (was 333);
        # features_for_assessment() still returns 333.
        "features_total": 371,
        "features_for_assessment": 333,
        "min_joints": 150,
        "expected_qa_codes": [],
        "tag": "NGP 2023 multi-sheet (GAIL Kandla-Samakhiali)",
    },
    "1ZSZ_Pipeline_Listing_run2_.xlsx": {
        "sheet": "Defects",
        "header_idx": 1,
        # Same API change: dents / welds / cracks (69 of them) stay
        # visible in `run.features`. Cluster children (~2k) plus the
        # 69 non-ML push features_total from 15,040 to 15,100 and drop
        # assess from 13,037 to 13,029 (because some non-ML rows used
        # to be counted as assessable due to the prior filter ordering).
        "features_total": 15100,
        "features_for_assessment": 13029,
        "min_joints": 900,
        "expected_qa_codes": [],
        "tag": "NGP 2024 multi-sheet",
    },
    "10_inch_Kandla_to_Samakhiali__58_2_km_FR_Pipe_Tally_Rev_0.xlsx": {
        "sheet": "Metal Loss List",
        "header_idx": 3,
        "features_total": 79,
        "features_for_assessment": 79,
        "min_joints": 50,
        "expected_qa_codes": [QAFlagCode.COORDINATES_SWAPPED],
        "tag": "Athena 2018 multi-sheet (lat/lon swapped at source)",
    },
}


# ---------------------------------------------------------------------------
# Per-file fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def reader() -> ILIReader:
    return ILIReader()


# Shared cache so individual cross-cutting tests below don't re-read the same
# 136k-row file. Keyed by filename.
_CACHE: dict[str, object] = {}


def _read_cached(reader: ILIReader, fname: str):
    if fname not in _CACHE:
        path = EXAMPLES / fname
        if not path.exists():
            pytest.skip(f"example file not present: {fname}")
        _CACHE[fname] = reader.read(path, run_id=fname[:8])
    return _CACHE[fname]


@pytest.fixture(scope="module", params=sorted(EXPECTED.keys()))
def parsed(request, reader) -> tuple[str, "ILIRun", dict]:
    fname = request.param
    run = _read_cached(reader, fname)
    return fname, run, EXPECTED[fname]


# ---------------------------------------------------------------------------
# Per-file assertions — one block per requirement in the spec
# ---------------------------------------------------------------------------

class TestEachExampleFile:
    @staticmethod
    def _within_2pct(got, expected):
        if expected == 0:
            return got == 0
        lo, hi = int(expected * 0.98), int(expected * 1.02 + 0.999)
        return lo <= got <= hi

    def test_features_total_within_2pct_of_baseline(self, parsed):
        _fname, run, exp = parsed
        expected = exp["features_total"]
        assert self._within_2pct(len(run.features), expected), (
            f"features count drifted: got {len(run.features)}, "
            f"baseline {expected} (±2 %)"
        )

    def test_features_for_assessment_within_2pct(self, parsed):
        """Excludes cluster children — matches the PDF executive summary
        for files where that figure is known."""
        _fname, run, exp = parsed
        expected = exp["features_for_assessment"]
        got = len(run.features_for_assessment())
        assert self._within_2pct(got, expected), (
            f"features_for_assessment drifted: got {got}, baseline {expected} (±2 %)"
        )

    def test_expected_qa_flags_present(self, parsed):
        _fname, run, exp = parsed
        got_codes = {f.code for f in run.qa_flags}
        for expected_code in exp["expected_qa_codes"]:
            assert expected_code in got_codes, (
                f"missing expected QA flag {expected_code}; got {got_codes}"
            )

    def test_joint_count_above_minimum(self, parsed):
        _fname, run, exp = parsed
        assert len(run.joints) >= exp["min_joints"]

    def test_sheet_and_header_match_expectation(self, parsed):
        _fname, run, exp = parsed
        if exp["sheet"] is not None:
            assert run.sheet_name == exp["sheet"]
        assert run.header_row_idx == exp["header_idx"]

    def test_all_required_canonical_fields_in_column_map(self, parsed):
        _fname, run, _exp = parsed
        for f in _REQUIRED_FIELDS_ON_FEATURE:
            # joint_number is required; columns named "surface" / "wt_mm" etc.
            # must have resolved to a real column index.
            pass
        for f in ("abs_distance_m", "joint_number", "depth_pct_wt",
                  "length_mm", "width_mm", "surface", "wt_mm"):
            assert f in run.column_map, (
                f"required canonical field {f!r} not mapped in {run.sheet_name!r}; "
                f"mapped: {sorted(run.column_map)}"
            )

    def test_no_none_in_core_feature_fields(self, parsed):
        """Every feature must have a non-None joint_number, abs_distance, depth."""
        _fname, run, _exp = parsed
        assert run.features, "reader produced zero features"
        offenders: list[str] = []
        for f in run.features[:5000]:  # cap for very large files
            if f.joint_number is None:
                offenders.append(f"joint_number None on row {f.source_row}")
                break
            if f.abs_distance_m is None:
                offenders.append(f"abs_distance None on row {f.source_row}")
                break
            if f.depth_pct_wt is None:
                offenders.append(f"depth None on row {f.source_row}")
                break
        assert not offenders, offenders

    def test_audit_trail_populated(self, parsed):
        _fname, run, _exp = parsed
        assert run.rows_read > 0
        assert run.column_map
        # rows_filtered may legitimately be empty (e.g. Athena 2018 ML List
        # is pre-filtered upstream) — only check the dict exists.
        assert isinstance(run.rows_filtered, dict)


# ---------------------------------------------------------------------------
# Cross-cutting checks (one test for the whole spec)
# ---------------------------------------------------------------------------

class TestClockHandlesBothFormats:
    """Clock column is parsed correctly regardless of whether Excel stored it
    as a datetime.time (most NGP files) or as a string (older Athena tallies).
    """

    def test_ngp_datetime_time_path(self, reader):
        # 1YCF's clock column is `datetime.time(5, 46)` for row 2.
        run = _read_cached(reader, "1YCF_Pipeline_Listing__run2_.xlsx")
        # First feature in the file corresponds to that row.
        first = run.features[0]
        # 5:46  ->  5 + 46/60 = 5.7666...
        assert first.clock_decimal_hours == pytest.approx(5 + 46 / 60.0)

    def test_athena_2018_time_in_metal_loss_list(self, reader):
        # Metal Loss List stores `datetime.time(5, 20)` for the first row.
        run = _read_cached(
            reader, "10_inch_Kandla_to_Samakhiali__58_2_km_FR_Pipe_Tally_Rev_0.xlsx"
        )
        first = run.features[0]
        assert first.clock_decimal_hours == pytest.approx(5 + 20 / 60.0)


class TestSurfaceNormalisation:
    """The reader maps every known surface variant -> Surface enum, via
    value_normalisations in column_synonyms.yaml."""

    @pytest.mark.parametrize(
        "fname,expected",
        [
            ("1YCF_Pipeline_Listing__run2_.xlsx", Surface.INTERNAL),       # "int."
            ("1ZSV_Pipeline_Listing.xlsx", Surface.INTERNAL),              # "int."
            (
                "10_inch_Kandla_to_Samakhiali__58_2_km_FR_Pipe_Tally_Rev_0.xlsx",
                Surface.INTERNAL,
            ),                                                              # "Internal"
        ],
    )
    def test_first_feature_surface(self, reader, fname, expected):
        run = _read_cached(reader, fname)
        assert run.features[0].surface is expected


class TestFeaturesForAssessment:
    """Cluster-aware accessor used for FFP counts."""

    def test_children_excluded(self, reader):
        # 1YCF: PDF says 29,479 children → 106,969 assessable. Reader
        # gets 29,479 children (exact) and 106,969 assessable (exact).
        # Note: post-dent-leak fix, total - assess includes BOTH cluster
        # children AND non-metal-loss features (dents / welds / cracks),
        # so we count children directly via cluster_parent_id.
        run = _read_cached(reader, "1YCF_Pipeline_Listing__run2_.xlsx")
        children = sum(
            1 for f in run.features if f.cluster_parent_id is not None
        )
        assert children == 29479, f"expected 29,479 cluster children, got {children}"

    def test_parents_kept(self, reader):
        run = _read_cached(reader, "1YCF_Pipeline_Listing__run2_.xlsx")
        # Every COCL parent must survive the filter.
        parents = [f for f in run.features if f.is_cluster_parent]
        assert parents, "no cluster parents found"
        assess_ids = {id(f) for f in run.features_for_assessment()}
        for p in parents:
            assert id(p) in assess_ids, f"parent {p.anomaly_id!r} dropped from assessment set"

    def test_no_children_when_no_description_column(self, reader):
        # NGP 2019 single-sheet has no Description column, so the reader
        # can't identify children — assessment count equals total.
        run = _read_cached(reader, "8-9100-13964_28IP1IP2_Pipe_Tally_run1_.xlsx")
        assert len(run.features_for_assessment()) == len(run.features)

    def test_assessment_subset_of_total(self, reader):
        for fname in EXPECTED:
            run = _read_cached(reader, fname)
            assess = run.features_for_assessment()
            assert len(assess) <= len(run.features)
            # No child snuck into the assessment set.
            assert all(f.cluster_parent_id is None for f in assess)


class TestFeatureIdentificationMapping:
    """Vendor free-text -> FeatureIdentification enum via value_normalisations."""

    def test_corr_via_text(self, reader):
        # NGP 2025: column has "Corrosion" (or POF Acronym "CORR" — synonym
        # precedence picks acronym).
        run = _read_cached(reader, "1YCF_Pipeline_Listing__run2_.xlsx")
        # First feature is "metal loss" / acronym CORR.
        assert run.features[0].feature_identification is FeatureIdentification.CORROSION

    def test_cocl_cluster_parent_flagged(self, reader):
        run = _read_cached(reader, "1YCF_Pipeline_Listing__run2_.xlsx")
        clusters = [
            f for f in run.features[:1000]
            if f.feature_identification is FeatureIdentification.CORROSION_CLUSTER
        ]
        assert clusters, "no COCL parents found in first 1000 features"
        assert all(c.is_cluster_parent for c in clusters)


class TestLatLonChecks:
    """Reader emits QA flags for coordinate sanity, configurable per project."""

    def test_swap_flag_emitted_and_values_fixed(self, reader):
        run = _read_cached(
            reader, "10_inch_Kandla_to_Samakhiali__58_2_km_FR_Pipe_Tally_Rev_0.xlsx"
        )
        codes = [f.code for f in run.qa_flags]
        assert QAFlagCode.COORDINATES_SWAPPED in codes, (
            f"expected COORDINATES_SWAPPED in {codes}"
        )
        # After swap: lat ~ 22-24°, lon ~ 69-77° (India).
        lats = [f.latitude for f in run.features if f.latitude is not None]
        lons = [f.longitude for f in run.features if f.longitude is not None]
        assert lats and lons
        assert 20 < max(lats) < 30, f"lat range looks wrong: max={max(lats)}"
        assert 65 < max(lons) < 80, f"lon range looks wrong: max={max(lons)}"

    def test_well_oriented_file_emits_no_lat_lon_flag(self, reader):
        # 1YCF is well-oriented (lat ~23, lon ~70) — no flag expected.
        run = _read_cached(reader, "1YCF_Pipeline_Listing__run2_.xlsx")
        codes = [f.code for f in run.qa_flags]
        assert QAFlagCode.COORDINATES_SWAPPED not in codes
        assert QAFlagCode.LAT_LON_OUT_OF_BOUNDS not in codes

    def test_out_of_bounds_flag_when_coords_make_no_sense(self, tmp_path):
        """Build a tiny synthetic file whose coords fall outside both
        orientations of the India box — reader must emit
        LAT_LON_OUT_OF_BOUNDS (not silently swap or accept)."""
        import openpyxl
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Defects"
        ws.append([
            "Abs. Distance, m", "Joint Number", "WT, mm", "Depth, %",
            "Length, mm", "Width, mm", "Surface", "POF Acronym",
            "Latitude", "Longitude",
        ])
        # Atlantic Ocean coords (lat 0, lon -30) — far from India and from any
        # swap that would still hit India.
        for i in range(5):
            ws.append([i * 10.0, 10 + i, 8.7, 25.0, 30.0, 40.0, "int.", "CORR", 0.0, -30.0])
        path = tmp_path / "oob.xlsx"
        wb.save(path)
        wb.close()

        run = ILIReader().read(path, run_id="oob")
        codes = [f.code for f in run.qa_flags]
        assert QAFlagCode.LAT_LON_OUT_OF_BOUNDS in codes, codes
        # Crucially: no silent swap happened.
        assert all(f.latitude == 0.0 for f in run.features)
        assert all(f.longitude == -30.0 for f in run.features)

    def test_coordinate_bounds_override(self, tmp_path):
        """Passing a custom bounding box should accept the same file that
        would otherwise be OOB."""
        import openpyxl
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Defects"
        ws.append([
            "Abs. Distance, m", "Joint Number", "WT, mm", "Depth, %",
            "Length, mm", "Width, mm", "Surface", "POF Acronym",
            "Latitude", "Longitude",
        ])
        for i in range(5):
            ws.append([i * 10.0, 10 + i, 8.7, 25.0, 30.0, 40.0, "int.", "CORR", 0.0, -30.0])
        path = tmp_path / "atlantic.xlsx"
        wb.save(path)
        wb.close()

        run = ILIReader(
            coordinate_bounds={"lat": [-10, 10], "lon": [-40, -20]}
        ).read(path, run_id="r")
        codes = [f.code for f in run.qa_flags]
        assert QAFlagCode.LAT_LON_OUT_OF_BOUNDS not in codes
        assert QAFlagCode.COORDINATES_SWAPPED not in codes


# ---------------------------------------------------------------------------
# Malformed-file rejection
# ---------------------------------------------------------------------------

class TestRejectsMalformedFile:
    def test_random_columns_raises_value_error(self, reader, tmp_path):
        import openpyxl
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Garbage"
        ws.append(["Foo", "Bar", "Baz", "Qux", "Frob", "Nicknack"])
        ws.append([1, 2, 3, 4, 5, 6])
        ws.append([7, 8, 9, 10, 11, 12])
        path = tmp_path / "garbage.xlsx"
        wb.save(path)
        wb.close()

        with pytest.raises(ValueError) as exc:
            reader.read(path, run_id="bad")
        # Error message must enumerate what was seen + what was tried.
        msg = str(exc.value)
        assert "missing" in msg.lower() or "no sheet" in msg.lower()

    def test_partial_columns_lists_missing_fields(self, reader, tmp_path):
        """A sheet with a couple of canonical columns but not all required ones
        should produce a ValueError that names what was missing."""
        import openpyxl
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Half"
        ws.append([
            "Abs. Distance, m", "Joint Number", "Wall Thickness, mm",
            "Depth, %", "Length, mm",  # missing width + surface
        ])
        ws.append([100.0, 10, 8.7, 25.0, 30])
        path = tmp_path / "half.xlsx"
        wb.save(path)
        wb.close()

        with pytest.raises(ValueError) as exc:
            reader.read(path, run_id="bad")
        msg = str(exc.value).lower()
        # Must mention at least one of the missing fields.
        assert "width_mm" in msg or "surface" in msg

    def test_nonexistent_file_raises_filenotfound(self, reader):
        with pytest.raises(FileNotFoundError):
            reader.read(EXAMPLES / "this_file_does_not_exist.xlsx", run_id="x")

    def test_garbage_magic_bytes_raises(self, reader, tmp_path):
        bogus = tmp_path / "fake.xlsx"
        bogus.write_bytes(b"\x00\x01\x02\x03GARBAGE")
        with pytest.raises(ValueError, match="unrecognised file format"):
            reader.read(bogus, run_id="x")


# ---------------------------------------------------------------------------
# Header normalisation primitive — guard against regressions
# ---------------------------------------------------------------------------

class TestHeaderNormalisation:
    @pytest.mark.parametrize(
        "raw,expected",
        [
            ("Abs. Distance, m", "abs distance m"),
            ("Wall Thickness, (mm)", "wall thickness mm"),
            ("Orientation, h:min", "orientation h min"),
            ("Orientation, h : min", "orientation h min"),         # spaces around colon
            ("Depth, %WT/ OD", "depth wt od"),                     # the % and / collapse
            ("Psafe, kg/cm²", "psafe kg cm2"),                      # NFKC turns ² into 2; that 2 stays
            (None, ""),
            ("Latitude, °", "latitude"),                           # ° collapses
        ],
    )
    def test_norm(self, raw, expected):
        assert _norm(raw) == expected


# ---------------------------------------------------------------------------
# Dent-leak regression: NGP-style "Dent complex" / DENC must be filtered.
# ---------------------------------------------------------------------------

# 1ZYC is the Abu Road Run-2 pipe tally. Not always checked into the repo
# (vendor file, often too large for git). The integration test below is
# skipped when the file isn't present.
_ABU_ROAD_RUN2 = EXAMPLES / "1ZYC_Pipeline_Listing.xlsx"


class TestDentFiltering:
    """Confirm dents never reach features_for_assessment().

    Real-world bug: feature 1637 in the Abu Road 1ZYC file was tagged
    "Dent complex" / DENC and slipped into FFP because the value-
    normalisation map didn't include "Dent complex". The reader treated
    the row as UNDEFINED, which doesn't match _NON_METAL_LOSS_FIDS, and
    the FFP engine then interpreted the 0.9 %OD depth as 90 %WT,
    producing ERF = 8.57 (vs the published max ERF ~0.9).
    """

    @pytest.mark.parametrize("dent_label", [
        # Strings that real vendor files have produced — all must
        # normalise to DENT and therefore be filtered.
        "Dent complex",
        "Dent plain",
        "dent kinked",
        "DENC",
        "DENP",
        "DENK",
        "Dent with additional feature",
    ])
    def test_dent_labels_normalise_to_DENT_enum(self, dent_label, tmp_path):
        """Build a tiny synthetic NGP-style sheet and confirm the reader
        normalises every dent variant to FeatureIdentification.DENT,
        and that all such rows are filtered out of
        features_for_assessment()."""
        import openpyxl
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Defects"
        # Header row + one CORR row + one dent row. The reader needs ≥3
        # canonical-field hits to pick the sheet — we provide plenty.
        ws.append([
            "Anomaly ID", "Absolute Distance, m", "Joint Number",
            "WT, mm", "Depth, %WT", "Length, mm", "Width, mm",
            "Surface", "POF Acronym", "Description",
        ])
        ws.append([
            "1", 100.0, 1, 7.1, 25.0, 50.0, 20.0,
            "Internal", "CORR", "metal loss",
        ])
        ws.append([
            "1637", 200.0, 2, 7.1, 0.9, 50.0, 20.0,
            "Internal", dent_label, "area of dent",
        ])
        pdf_path = tmp_path / "dent_test.xlsx"
        wb.save(pdf_path)

        reader = ILIReader()
        run = reader.read(str(pdf_path), run_id="run_test")

        # Both rows should be in the raw feature list.
        assert len(run.features) >= 2, (
            f"only {len(run.features)} features parsed — sheet detection "
            "or column resolution failed"
        )

        # Find feature 1637 — confirm it exists and is tagged DENT.
        f1637 = next(
            (f for f in run.features if f.anomaly_id == "1637"), None,
        )
        assert f1637 is not None, "feature 1637 missing from raw features"
        assert f1637.feature_identification == FeatureIdentification.DENT, (
            f"vendor label {dent_label!r} should normalise to DENT, got "
            f"{f1637.feature_identification!r}"
        )

        # And it must NOT be in features_for_assessment().
        assess_ids = {f.anomaly_id for f in run.features_for_assessment()}
        assert "1637" not in assess_ids, (
            f"DENT feature 1637 (vendor label {dent_label!r}) leaked into "
            "features_for_assessment() — the non_metal_loss filter is "
            "missing this code path"
        )

    def test_unknown_dent_string_produces_parse_warning(self, tmp_path):
        """When a vendor string CAN'T be normalised but looks dent-like,
        the reader records an UNRECOGNISED_NON_ML_FID parse warning so a
        maintainer notices and extends column_synonyms.yaml."""
        import openpyxl
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "Defects"
        ws.append([
            "Anomaly ID", "Absolute Distance, m", "Joint Number",
            "WT, mm", "Depth, %WT", "Length, mm", "Width, mm",
            "Surface", "POF Acronym",
        ])
        ws.append([
            "1", 100.0, 1, 7.1, 25.0, 50.0, 20.0, "Internal", "CORR",
        ])
        ws.append([
            "9999", 200.0, 2, 7.1, 0.9, 50.0, 20.0,
            "Internal", "Dent with weird hyperspace anomaly",  # unknown variant
        ])
        path = tmp_path / "unknown_dent.xlsx"
        wb.save(path)

        run = ILIReader().read(str(path), run_id="run_test")
        warnings = [w for w in run.parse_warnings if "UNRECOGNISED_NON_ML_FID" in w]
        assert warnings, (
            "expected an UNRECOGNISED_NON_ML_FID warning for unknown dent "
            f"variant; got parse_warnings = {run.parse_warnings}"
        )


# ---------------------------------------------------------------------------
# Integration test against the real Abu Road Run-2 (1ZYC) — skipped when
# the file isn't checked into the repo.
# ---------------------------------------------------------------------------

@pytest.mark.skipif(
    not _ABU_ROAD_RUN2.exists(),
    reason=(
        f"Real Abu Road Run-2 pipe tally not present at "
        f"{_ABU_ROAD_RUN2.name}. Drop the vendor file there to exercise "
        "this test."
    ),
)
class TestAbuRoadDentLeak:
    """Real-data regression: feature 1637 in the Abu Road Run-2 file must
    be filtered out of features_for_assessment() — it's a dent, not a
    metal-loss feature, and the FFP engine isn't valid for it."""

    @pytest.fixture(scope="class")
    def run(self):
        return ILIReader().read(str(_ABU_ROAD_RUN2), run_id="run_2")

    def test_feature_1637_in_raw_features(self, run):
        """Sanity: the row IS present in run.features."""
        f1637 = next(
            (f for f in run.features if f.anomaly_id == "1637"), None,
        )
        assert f1637 is not None, (
            "Feature 1637 not in raw features at all — sheet/column "
            "resolution may have changed."
        )

    def test_feature_1637_is_a_dent(self, run):
        """The fid must resolve to DENT after value normalisation."""
        f1637 = next(
            (f for f in run.features if f.anomaly_id == "1637"), None,
        )
        assert f1637 is not None
        assert f1637.feature_identification == FeatureIdentification.DENT, (
            f"got fid = {f1637.feature_identification!r} "
            f"(raw description = {f1637.raw_description!r})"
        )

    def test_feature_1637_not_in_features_for_assessment(self, run):
        """The whole point of this regression test."""
        assess_ids = {f.anomaly_id for f in run.features_for_assessment()}
        assert "1637" not in assess_ids, (
            "Feature 1637 is a dent and must not be FFP-assessed. "
            "If you see this fail, check value_normalisations.feature_"
            "identification in config/column_synonyms.yaml for the "
            "actual vendor string used on row 1637."
        )
